#pragma once

#include <curses.h>


constexpr short
MENU_ODD_FG_COLOR = 8,
MENU_ODD_BG_COLOR = 9,
MENU_ODD_PAIR = 1,
MENU_EVEN_FG_COLOR = 10,
MENU_EVEN_BG_COLOR = 11,
MENU_EVEN_PAIR = 2,
SUBMENU_ODD_FG_COLOR = 12,
SUBMENU_ODD_BG_COLOR = 13,
SUBMENU_ODD_PAIR = 3,
SUBMENU_EVEN_FG_COLOR = 14,
SUBMENU_EVEN_BG_COLOR = 15,
SUBMENU_EVEN_PAIR = 4,
ALERT_FG_COLOR = 16,
ALERT_BG_COLOR = 17,
ALERT_PAIR = 5,
PARAM_FG_COLOR = 18,
PARAM_BG_COLOR = 19,
PARAM_PAIR = 6,
BUFFER_FG_COLOR = 20,
BUFFER_BG_COLOR = 21,
BUFFER_PAIR = 7,
HELP_ODD_FG_COLOR = 22,
HELP_ODD_BG_COLOR = 23,
HELP_ODD_PAIR = 8,
HELP_EVEN_FG_COLOR = 24,
HELP_EVEN_BG_COLOR = 25,
HELP_EVEN_PAIR = 9;