#pragma once


constexpr int
TOP_MARGIN_LEFT = 1,
TOP_MARGIN_RIGHT = 1,
TOP_MARGINS = TOP_MARGIN_LEFT + TOP_MARGIN_RIGHT,
OPTION_MARGIN_LEFT = 2,
OPTION_MARGIN_RIGHT = 2,
OPTION_MARGINS = OPTION_MARGIN_LEFT + OPTION_MARGIN_RIGHT,
ALERT_HORIZONTAL_MARGINS = 2,
ALERT_VERTICAL_MARGINS = 2,
PARAM_HORIZONTAL_MARGINS = 2,
PARAM_VERTICAL_MARGINS = 2,
PARAM_BETWEEN_MARGIN = 1;